#!/bin/sh
SCRIPT="java -jar /opt/watchcat/bin/watchcat-node.jar"
RUNAS=root
 
PIDFILE=/tmp/watchcat.pid
LOGFILE=/var/log/watchcat/node.log
 
start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting Watchcat Node' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Watchcat Node started' >&2
}
 
stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Watchcat Node not running' >&2
    return 1
  fi
  echo 'Watchcat Node Collector' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Watchcat Node stopped' >&2
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac